plugins {
    id 'com.android.application'
}

android {
    namespace 'com.fastsong.android'
    compileSdk 34

    defaultConfig {
        applicationId "com.fastsong.android"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'com.google.android.gms:play-services-ads:23.1.0'
}
